"use client";

import { ColumnDef } from "@tanstack/react-table";

type Payment = {
  id: string;
  amount: number;
  status: "pending" | "processing" | "success" | "failed";
  email: string;
};

type Exam = {
  title: string;
  class: string;
  code: string;
  participants: number;
  submit: string;
  scheduleStart: string;
  scheduleEnd: string;
  status: string;
};
export const examsData: Exam[] = [
  {
    title: "Basic Programming",
    class: "TECH-3A",
    code: "zhPxTdVu",
    participants: 34,
    submit: "23/34",
    scheduleStart: "14 March 2024",
    scheduleEnd: "17 March 2024",
    status: "Running",
  },
  {
    title: "Advanced Algorithms",
    class: "TECH-4B",
    code: "xYT34PpL",
    participants: 28,
    submit: "27/28",
    scheduleStart: "10 March 2024",
    scheduleEnd: "15 March 2024",
    status: "Running",
  },
  {
    title: "Data Structures",
    class: "TECH-2C",
    code: "DTR90zVu",
    participants: 40,
    submit: "35/40",
    scheduleStart: "12 March 2024",
    scheduleEnd: "16 March 2024",
    status: "Running",
  },
  {
    title: "Computer Networks",
    class: "TECH-3D",
    code: "qWEr98Ty",
    participants: 25,
    submit: "20/25",
    scheduleStart: "11 March 2024",
    scheduleEnd: "14 March 2024",
    status: "Running",
  },
  {
    title: "Operating Systems",
    class: "TECH-4A",
    code: "OpSys123",
    participants: 30,
    submit: "29/30",
    scheduleStart: "15 March 2024",
    scheduleEnd: "19 March 2024",
    status: "Running",
  },
  {
    title: "Database Management",
    class: "TECH-3B",
    code: "DBMng345",
    participants: 37,
    submit: "30/37",
    scheduleStart: "13 March 2024",
    scheduleEnd: "18 March 2024",
    status: "Running",
  },
  {
    title: "Machine Learning",
    class: "TECH-5A",
    code: "MLxyz89",
    participants: 42,
    submit: "40/42",
    scheduleStart: "16 March 2024",
    scheduleEnd: "20 March 2024",
    status: "Running",
  },
  {
    title: "Web Development",
    class: "TECH-2B",
    code: "WebD321",
    participants: 29,
    submit: "28/29",
    scheduleStart: "14 March 2024",
    scheduleEnd: "18 March 2024",
    status: "Running",
  },
  {
    title: "Cybersecurity Basics",
    class: "TECH-4C",
    code: "Cyber999",
    participants: 22,
    submit: "20/22",
    scheduleStart: "13 March 2024",
    scheduleEnd: "17 March 2024",
    status: "Running",
  },
  {
    title: "Artificial Intelligence",
    class: "TECH-5B",
    code: "AI00456",
    participants: 45,
    submit: "42/45",
    scheduleStart: "10 March 2024",
    scheduleEnd: "14 March 2024",
    status: "Running",
  },
  {
    title: "Mobile App Development",
    class: "TECH-3C",
    code: "MobDev22",
    participants: 33,
    submit: "30/33",
    scheduleStart: "12 March 2024",
    scheduleEnd: "15 March 2024",
    status: "Running",
  },
  {
    title: "Software Engineering",
    class: "TECH-4D",
    code: "SoftEng2",
    participants: 38,
    submit: "35/38",
    scheduleStart: "11 March 2024",
    scheduleEnd: "16 March 2024",
    status: "Running",
  },
  {
    title: "Embedded Systems",
    class: "TECH-3E",
    code: "EmbedSys",
    participants: 27,
    submit: "25/27",
    scheduleStart: "15 March 2024",
    scheduleEnd: "19 March 2024",
    status: "Running",
  },
  {
    title: "Cloud Computing",
    class: "TECH-5C",
    code: "Cloud999",
    participants: 40,
    submit: "38/40",
    scheduleStart: "14 March 2024",
    scheduleEnd: "17 March 2024",
    status: "Running",
  },
  {
    title: "DevOps Basics",
    class: "TECH-4E",
    code: "DevOpsX",
    participants: 31,
    submit: "30/31",
    scheduleStart: "10 March 2024",
    scheduleEnd: "15 March 2024",
    status: "Running",
  },
  {
    title: "Digital Signal Processing",
    class: "TECH-3F",
    code: "DSP2024",
    participants: 26,
    submit: "23/26",
    scheduleStart: "12 March 2024",
    scheduleEnd: "16 March 2024",
    status: "Running",
  },
  {
    title: "Natural Language Processing",
    class: "TECH-5D",
    code: "NLP9988",
    participants: 39,
    submit: "37/39",
    scheduleStart: "11 March 2024",
    scheduleEnd: "15 March 2024",
    status: "Running",
  },
  {
    title: "Data Science",
    class: "TECH-4F",
    code: "DS2024X",
    participants: 32,
    submit: "30/32",
    scheduleStart: "16 March 2024",
    scheduleEnd: "20 March 2024",
    status: "Running",
  },
  {
    title: "Information Retrieval",
    class: "TECH-5E",
    code: "IRTech24",
    participants: 44,
    submit: "42/44",
    scheduleStart: "13 March 2024",
    scheduleEnd: "17 March 2024",
    status: "Running",
  },
  {
    title: "Quantum Computing",
    class: "TECH-5F",
    code: "QComp98",
    participants: 36,
    submit: "35/36",
    scheduleStart: "14 March 2024",
    scheduleEnd: "19 March 2024",
    status: "Running",
  },
  {
    title: "Digital Electronics",
    class: "TECH-3G",
    code: "DigEl99",
    participants: 28,
    submit: "25/28",
    scheduleStart: "10 March 2024",
    scheduleEnd: "15 March 2024",
    status: "Running",
  },
  {
    title: "Blockchain Technology",
    class: "TECH-4G",
    code: "BlockC32",
    participants: 35,
    submit: "32/35",
    scheduleStart: "12 March 2024",
    scheduleEnd: "16 March 2024",
    status: "Running",
  },
  {
    title: "Game Development",
    class: "TECH-3H",
    code: "GameDev7",
    participants: 29,
    submit: "27/29",
    scheduleStart: "11 March 2024",
    scheduleEnd: "15 March 2024",
    status: "Running",
  },
  {
    title: "E-commerce Development",
    class: "TECH-4H",
    code: "Ecom777",
    participants: 41,
    submit: "39/41",
    scheduleStart: "15 March 2024",
    scheduleEnd: "19 March 2024",
    status: "Running",
  },
  {
    title: "Human-Computer Interaction",
    class: "TECH-4I",
    code: "HCI3422",
    participants: 30,
    submit: "28/30",
    scheduleStart: "14 March 2024",
    scheduleEnd: "18 March 2024",
    status: "Running",
  },
  {
    title: "IoT Applications",
    class: "TECH-5G",
    code: "IoT786",
    participants: 42,
    submit: "40/42",
    scheduleStart: "13 March 2024",
    scheduleEnd: "17 March 2024",
    status: "Running",
  },
  {
    title: "Digital Marketing",
    class: "TECH-3I",
    code: "DigMark1",
    participants: 37,
    submit: "35/37",
    scheduleStart: "11 March 2024",
    scheduleEnd: "15 March 2024",
    status: "Running",
  },
  {
    title: "Augmented Reality",
    class: "TECH-5H",
    code: "ARTech88",
    participants: 45,
    submit: "43/45",
    scheduleStart: "10 March 2024",
    scheduleEnd: "14 March 2024",
    status: "Running",
  },
  {
    title: "Virtual Reality",
    class: "TECH-5I",
    code: "VRX2024",
    participants: 39,
    submit: "38/39",
    scheduleStart: "15 March 2024",
    scheduleEnd: "19 March 2024",
    status: "Running",
  },
  {
    title: "Software Testing",
    class: "TECH-4J",
    code: "TestQA44",
    participants: 33,
    submit: "31/33",
    scheduleStart: "14 March 2024",
    scheduleEnd: "18 March 2024",
    status: "Running",
  },
];

export const payments: Payment[] = [
  {
    id: "728ed52f",
    amount: 100,
    status: "pending",
    email: "m@example.com",
  },
  {
    id: "489e1d42",
    amount: 125,
    status: "processing",
    email: "example@gmail.com",
  },
  // ...
];

export const columns: ColumnDef<Exam>[] = [
  {
    accessorKey: "title",
    header: () => <div className="pl-3">Title</div>,
    cell: ({ row }) => {
      const value = row.original.title;

      return <div className="my-2 pl-3 font-medium">{value}</div>;
    },
  },
  {
    accessorKey: "code",
    header: "Code",
  },
  {
    accessorKey: "participants",
    header: "Participants",
  },
  {
    accessorKey: "submit",
    header: "Submit",
  },
  {
    accessorKey: "scheduleStart",
    header: "Schedule Start",
  },
  {
    accessorKey: "scheduleEnd",
    header: "Schedule End",
  },
  {
    accessorKey: "status",
    header: "Status",
  },
];
